
AWS_SES_REGION_ENDPOINT: email.us-east-1.amazonaws.com
AWS_SES_REGION_NAME: us-east-1
BACKEND_SERVICE_EDX_OAUTH2_KEY: ecommerce-backend-client
BACKEND_SERVICE_EDX_OAUTH2_SECRET: ecommerce-backend-client-secret
BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL: https://lms/oauth2
CACHES:
    default:
        BACKEND: django.core.cache.backends.memcached.MemcachedCache
        KEY_PREFIX: discovery
        LOCATION:
        - memcache:11211
CSRF_COOKIE_SECURE: false
CORS_ORIGIN_WHITELIST:
    - https://lms
    - https://analytics
    - https://ecommerce
DATABASES:
    default:
        ATOMIC_REQUESTS: false
        CONN_MAX_AGE: 60
        ENGINE: django.db.backends.mysql
        HOST: mysql
        NAME: discoverydb
        OPTIONS:
            connect_timeout: 10
            init_command: SET sql_mode='STRICT_TRANS_TABLES'
        PASSWORD: pwd
        PORT: '3306'
        USER: discovery
DEFAULT_PARTNER_ID: 1
EDX_DRF_EXTENSIONS:
    OAUTH2_USER_INFO_URL: https://lms/oauth2/user_info
ELASTICSEARCH_INDEX_NAME: catalog
ELASTICSEARCH_URL: http://elasticsearch:9200/
EMAIL_BACKEND: django_ses.SESBackend
EMAIL_HOST: localhost
EMAIL_HOST_PASSWORD: ''
EMAIL_HOST_USER: ''
EMAIL_PORT: 25
EMAIL_USE_TLS: false
EXTRA_APPS: []
LOCAL_DISCOVERY_MEDIA_URL: /media/
JWT_AUTH:
    JWT_ALGORITHM: HS256
    JWT_AUTH_COOKIE_HEADER_PAYLOAD: edx-jwt-cookie-header-payload
    JWT_AUTH_COOKIE_SIGNATURE: edx-jwt-cookie-signature
    JWT_AUTH_REFRESH_COOKIE: edx-jwt-refresh-cookie
    JWT_ISSUERS:
    -   AUDIENCE: eol
        ISSUER: https://lms/oauth2/
        SECRET_KEY: jwt_secret
    JWT_PRIVATE_SIGNING_JWK: priv
    JWT_PUBLIC_SIGNING_JWK_SET: pub
    JWT_SIGNING_ALGORITHM: RS512
    JWT_SECRET_KEY: jwt_secret
LANGUAGE_CODE: en
MEDIA_STORAGE_BACKEND:
    DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
    MEDIA_ROOT: /edx/var/discovery/media
    MEDIA_URL: /media/
OPENEXCHANGERATES_API_KEY: ''
PARLER_DEFAULT_LANGUAGE_CODE: en
PARLER_LANGUAGES:
    1:
    -   code: en
    default:
        fallbacks:
        - en
        hide_untranslated: 'False'
PLATFORM_NAME: Eol
PUBLISHER_FROM_EMAIL: eol-ayuda.uchile.cl
SECRET_KEY: key
SESSION_EXPIRE_AT_BROWSER_CLOSE: false
SOCIAL_AUTH_EDX_OAUTH2_ISSUER: https://lms
SOCIAL_AUTH_EDX_OAUTH2_KEY: key
SOCIAL_AUTH_EDX_OAUTH2_LOGOUT_URL: https://lms/logout
SOCIAL_AUTH_EDX_OAUTH2_SECRET: secret
SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT: https://lms
SOCIAL_AUTH_EDX_OAUTH2_PUBLIC_URL_ROOT: https://lms
SOCIAL_AUTH_REDIRECT_IS_HTTPS: true
STATICFILES_STORAGE: whitenoise.storage.CompressedStaticFilesStorage
TIME_ZONE: UTC
