name: Docker Image CI

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'eol/koa'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file .github/Dockerfile --tag ghcr.io/eol-uchile/discovery:${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/eol/koa' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Github Container Registry
        if: ${{ github.ref == 'refs/heads/eol/koa' }}
        run: |
          docker push ghcr.io/eol-uchile/discovery:${GITHUB_SHA}
